######################################################################
# Automatically generated by qmake (2.01a) ? 6? 7 10:33:24 2017
######################################################################

CONFIG += qwt

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += displaysysinfo.h getnode.h
FORMS += displaysysinfo.ui
SOURCES += displaysysinfo.cpp getnode.cpp main.cpp
